name: Run Tests
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: install bats
        run: yarn
      - name: install gg
        run: |
          sudo mv -fv ./bin/gg /usr/local/bin/gg
          chmod -v +x /usr/local/bin/gg
      - name: test
        run: yarn test
